/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzj_ndk_demo_fromc_OutText */

#ifndef _Included_com_lzj_ndk_demo_fromc_OutText
#define _Included_com_lzj_ndk_demo_fromc_OutText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzj_ndk_demo_fromc_OutText
 * Method:    say
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzj_ndk_demo_fromc_OutText_say
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
